# Generated by Django 6.0.2 on 2026-04-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='school',
            field=models.CharField(choices=[('AGS', 'Auckland Grammar School'), ('STC', "St Cuthbert's College"), ('STK', "St Kent's College"), ('BAR', 'Baradene College'), ('EGG', "Epsom Girl's College"), ('KC', "King's College"), ('GDC', 'Glendowie College'), ('Selwyn', 'Selwyn College')], max_length=100),
        ),
    ]
