# Generated by Django 6.0.2 on 2026-04-09 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_member_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='surname',
            new_name='last_name',
        ),
    ]
