# Generated by Django 6.0.2 on 2026-04-10 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_initiatives_seminars'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiatives',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seminars',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 4, 10, 19, 48, 8, 955510, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='seminars',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='school',
            field=models.CharField(choices=[('AGS', 'Auckland Grammar School'), ('STC', "St Cuthbert's College"), ('STK', "St Kent's College"), ('BAR', 'Baradene College'), ('EGG', "Epsom Girl's College"), ('KC', "King's College"), ('GDC', 'Glendowie College'), ('selwyn', 'Selwyn College'), ('other', 'Other')], max_length=100),
        ),
    ]
