# Generated by Django 6.0.2 on 2026-04-10 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_initiatives_hidden_seminars_date_seminars_hidden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminars',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 4, 10, 20, 5, 36, 560984, tzinfo=datetime.timezone.utc)),
        ),
    ]
