# Generated by Django 6.0.2 on 2026-04-10 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_seminars_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminars',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 4, 10, 20, 17, 27, 346252, tzinfo=datetime.timezone.utc)),
        ),
    ]
