# Generated by Django 6.0.2 on 2026-04-10 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_initiative_seminar_delete_initiatives_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 4, 10, 21, 31, 4, 767399, tzinfo=datetime.timezone.utc)),
        ),
    ]
