# Generated by Django 6.0.2 on 2026-04-10 21:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_seminar_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 4, 10, 21, 40, 37, 831608, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.datetime(2026, 4, 10, 21, 40, 37, 832122, tzinfo=datetime.timezone.utc))),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.initiative')),
            ],
        ),
    ]
