# Generated by Django 6.0.2 on 2026-04-10 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_seminar_date_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='date',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='status',
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 10, 22, 14, 58, 531424, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 10, 22, 14, 58, 531418, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='seminar',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 10, 22, 14, 58, 531173, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='seminar',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 10, 22, 14, 58, 531036, tzinfo=datetime.timezone.utc)),
        ),
    ]
