# Generated by Django 6.0.2 on 2026-04-10 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_event_end_time_alter_event_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pages.initiative'),
        ),
    ]
