# Generated by Django 6.0.2 on 2026-04-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_event_initiative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='school',
            field=models.CharField(choices=[('AGS', 'Auckland Grammar School'), ('STC', "St Cuthbert's College"), ('STK', "St Kent's College"), ('BAR', 'Baradene College'), ('EGG', "Epsom Girl's College"), ('KC', "King's College"), ('GDC', 'Glendowie College'), ('selwyn', 'Selwyn College'), ('DIO', 'Diocesan School For Girls'), ('other', 'Other')], max_length=100),
        ),
    ]
