# Generated by Django 6.0.2 on 2026-04-11 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_member_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee', models.CharField(choices=[('general', 'Board of Directors'), ('administrative', 'Administrative Committee'), ('technical', 'Technical Committee')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='pages.member')),
            ],
        ),
    ]
