# Generated by Django 6.0.2 on 2026-04-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_memberrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='year_level',
            field=models.IntegerField(choices=[(9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13')]),
        ),
        migrations.AlterField(
            model_name='memberrole',
            name='committee',
            field=models.CharField(choices=[('general', 'Board of Directors'), ('administrative', 'Administrative Committee'), ('technical', 'Technical Committee'), ('outreach', 'Outreach Department'), ('finance', 'Finance Department')], max_length=20),
        ),
    ]
