# Generated by Django 5.2 on 2026-04-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_blogpost_alter_event_end_time_alter_event_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
