# Generated by Django 5.2 on 2026-04-23 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_blogpost_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='hidden',
            new_name='approved',
        ),
    ]
