# Generated by Django 6.0.2 on 2026-05-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_rename_hidden_blogpost_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='discord_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
