# Generated by Django 5.2 on 2026-04-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_rename_hidden_blogpost_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='summary',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
