# Generated by Django 5.2 on 2026-04-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_initiative_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='description',
            field=models.TextField(),
        ),
    ]
