# Generated by Django 5.2 on 2026-05-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_alter_event_description_alter_initiative_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_img',
            field=models.ImageField(blank=True, null=True, upload_to='member_photos/'),
        ),
    ]
