# Generated by Django 5.2 on 2026-05-02 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_member_member_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member_img',
            new_name='photo',
        ),
    ]
