# Generated by Django 5.2 on 2026-05-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_rename_member_img_member_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='discord_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
