# Generated by Django 6.0.2 on 2026-05-10 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_member_discord_username'),
        ('pages', '0025_member_discord_username'),
    ]

    operations = [
    ]
