# Generated by Django 6.0.2 on 2026-05-10 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_merge_20260510_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tbc',
            field=models.BooleanField(default=False, verbose_name='TBC'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='initiative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='pages.initiative'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='school',
            field=models.CharField(choices=[('AGS', 'Auckland Grammar School'), ('STC', "St Cuthbert's College"), ('STK', "St Kent's College"), ('BAR', 'Baradene College'), ('EGGS', "Epsom Girl's Grammar School"), ('KC', "King's College"), ('GDC', 'Glendowie College'), ('selwyn', 'Selwyn College'), ('DIO', 'Diocesan School For Girls'), ('RGT', 'Rangitoto College'), ('DIL', 'Dilworth School'), ('ACGP', 'ACG Parnell College'), ('ACGS', 'ACG Sunderland'), ('WBC', "Westlake Boys' College"), ('WGC', "Westlake Girls' College"), ('MAC', "Maclean's College"), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='memberrole',
            name='committee',
            field=models.CharField(choices=[('general', 'Board of Directors'), ('eduunlocked', 'EduUnlocked Initiative'), ('nextgen', 'NextGen Change Initiative'), ('young_artists', 'Young Artists Initiative'), ('administrative', 'Administrative Committee'), ('technical', 'Technical Committee'), ('outreach', 'Outreach Department'), ('finance', 'Finance Department')], max_length=20),
        ),
        migrations.CreateModel(
            name='EventRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='pages.event')),
            ],
            options={
                'unique_together': {('event', 'email')},
            },
        ),
    ]
