# Generated by Django 6.0.2 on 2026-05-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_event_tbc_alter_event_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tbc',
        ),
        migrations.AddField(
            model_name='event',
            name='end_tbc',
            field=models.BooleanField(default=False, verbose_name='End time TBC'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_tbc',
            field=models.BooleanField(default=False, verbose_name='Start time TBC'),
        ),
    ]
