# Generated by Django 5.2 on 2026-05-10 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_event_tbc_alter_event_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrsvp',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='pages.member'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='eventrsvp',
            unique_together={('event', 'member')},
        ),
        migrations.RemoveField(
            model_name='eventrsvp',
            name='email',
        ),
        migrations.RemoveField(
            model_name='eventrsvp',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='eventrsvp',
            name='last_name',
        ),
    ]
