# Generated by Django 5.2 on 2026-05-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_alter_eventrsvp_unique_together_eventrsvp_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventrsvp',
            name='member',
        ),
        migrations.AddField(
            model_name='eventrsvp',
            name='first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventrsvp',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventrsvp',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
