# Generated by Django 5.2 on 2026-05-10 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_remove_eventrsvp_member_eventrsvp_first_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventrsvp',
            unique_together={('event', 'email')},
        ),
        migrations.AddField(
            model_name='eventrsvp',
            name='member',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='pages.member'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='eventrsvp',
            unique_together={('event', 'email'), ('event', 'member')},
        ),
    ]
