# Generated by Django 5.2 on 2026-05-10 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_alter_eventrsvp_unique_together_eventrsvp_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrsvp',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='pages.member'),
        ),
    ]
