# Generated by Django 5.2 on 2026-05-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_alter_eventrsvp_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='school',
            field=models.CharField(choices=[('AGS', 'Auckland Grammar School'), ('STC', "St Cuthbert's College"), ('STK', "St Kent's College"), ('BAR', 'Baradene College'), ('EGGS', "Epsom Girl's Grammar School"), ('KC', "King's College"), ('GDC', 'Glendowie College'), ('selwyn', 'Selwyn College'), ('DIO', 'Diocesan School For Girls'), ('RGT', 'Rangitoto College'), ('DIL', 'Dilworth School'), ('ACGP', 'ACG Parnell College'), ('ACGS', 'ACG Sunderland'), ('WBC', "Westlake Boys' College"), ('WGC', "Westlake Girls' College"), ('MAC', "Maclean's College"), ('SDCC', "St Dominic's Catholic College"), ('other', 'Other')], max_length=100),
        ),
    ]
