# Generated by Django 5.2 on 2026-05-24 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_alter_member_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='director',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to='pages.member'),
        ),
    ]
