# Generated by Django 5.2 on 2026-05-24 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_initiative_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to='pages.member'),
        ),
    ]
