# Generated by Django 6.0.2 on 2026-06-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_rename_committee_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='memberrole',
            name='committee',
            field=models.CharField(choices=[('general', 'Board of Directors'), ('ea', 'Eductional Advancement'), ('ype', 'Youth Political Engagement'), ('yac', 'Young Artists Collective'), ('administrative', 'Administrative Committee'), ('technical', 'Technical Committee'), ('outreach', 'Outreach Department'), ('finance', 'Finance Department')], max_length=20),
        ),
    ]
