# Generated by Django 6.0.2 on 2026-06-07 08:39

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_add_initiative_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to=pages.models.art_piece_path)),
                ('order', models.PositiveIntegerField(default=0)),
                ('hidden', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
