# Generated by Django 6.0.2 on 2026-06-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0038_add_artpiece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpiece',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
