# Generated by Django 5.2 on 2026-06-13 10:40

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_artpiece_title_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=pages.models.about_photo_path)),
                ('slot', models.CharField(choices=[('side', 'Side Photo'), ('middle', 'Middle Photo')], default='side', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
