# Generated by Django 5.2 on 2026-07-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0043_blogreaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='school',
            field=models.CharField(choices=[('AGS', 'Auckland Grammar School'), ('STC', "St Cuthbert's College"), ('STK', "St Kent's College"), ('BAR', 'Baradene College'), ('EGGS', "Epsom Girl's Grammar School"), ('KC', "King's College"), ('GDC', 'Glendowie College'), ('selwyn', 'Selwyn College'), ('DIO', 'Diocesan School For Girls'), ('RGT', 'Rangitoto College'), ('DIL', 'Dilworth School'), ('ACGP', 'ACG Parnell College'), ('ACGS', 'ACG Sunderland'), ('WBC', "Westlake Boys' College"), ('WGC', "Westlake Girls' College"), ('MAC', "Maclean's College"), ('SDCC', "St Dominic's Catholic College"), ('GBHS', 'Green Bay High School'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='memberrole',
            name='committee',
            field=models.CharField(choices=[('general', 'General Committee'), ('ea', 'Educational Advancement'), ('ype', 'Youth Political Engagement'), ('yac', 'Young Artists Collective'), ('administrative', 'Administrative Committee'), ('technical', 'Technical Committee'), ('outreach', 'Outreach Department'), ('finance', 'Finance Department')], max_length=20),
        ),
    ]
