# Generated by Django 5.2 on 2026-08-05 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0044_alter_member_school_alter_memberrole_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticketed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=2)),
                ('number', models.PositiveIntegerField()),
                ('is_accessible', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='pages.event')),
            ],
            options={
                'ordering': ['row', 'number'],
                'unique_together': {('event', 'row', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='pages.seat')),
            ],
        ),
    ]
