# Generated by Django 5.2 on 2026-08-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0045_event_ticketed_seat_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrole',
            name='committee',
            field=models.CharField(choices=[('general', 'General Committee'), ('ea', 'EduUnlocked'), ('ype', 'Youth Political Engagement'), ('yac', 'Young Artists Collective'), ('administrative', 'Administrative Committee'), ('technical', 'Technical Committee'), ('outreach', 'Outreach Department'), ('finance', 'Finance Department')], max_length=20),
        ),
    ]
